# mpLP reformulation of an energy systems MILP


\begin{equation}
    min \sum_{t \in \mathcal{T}^{net}} \sum_{p \in \mathcal{P}} Capex_{p,t} \times Cap^P_{p,t} + \sum_{t \in \mathcal{T}^{sch}} \sum_{r \in \mathcal{R}^{cons}}  Price_{r,t}  \times C_{r,t} + \sum_{t \in \mathcal{T}^{sch}} \sum_{p \in \mathcal{P}}  Vopex_{r,t} \times P_{r,t} 
\end{equation}


\begin{equation}
    Cap^S_{r,t} \leq Cap^{S-max}_{r,t} \times X^S_{r,t} \hspace{1cm} \forall r \in \mathcal{R}^{storage}, t \in \mathcal{T}^{net}
\end{equation}

\begin{equation}
    Cap^P_{p,t} \leq Cap^{P-max}_{p,t} \times X^P_p  \hspace{1cm} \forall p \in \mathcal{P}, t \in \mathcal{T}^{net}
\end{equation} 

\begin{equation}
    P_{p,t} \leq Cap^{P}_{p,t}  \hspace{1cm} \forall p \in \mathcal{P}, t \in \mathcal{T}^{sch}
\end{equation} 

\begin{equation}
    Inv_{r,t} \leq Cap^{S}_{r,t}  \hspace{1cm} \forall r \in \mathcal{R}^{storage}, t \in \mathcal{T}^{sch}
\end{equation} 


\begin{equation}
    - S_{r,t} \leq - D_{r,t}  \hspace{1cm} \forall r \in \mathcal{R}, t \in \mathcal{T}^{sch}
\end{equation}

\begin{equation}
    C_{r,t} \leq C^{max}_{r,t} \hspace{1cm} \forall r \in \mathcal{R}, t \in \mathcal{T}^{sch}
\end{equation}


\begin{equation}
    - S_{r,t} + \sum_{p \in \mathcal{P}} P_{p,t} \times \eta(p,r) = 0 \hspace{1cm} \forall r \in \mathcal{R}^{sell}, t \in \mathcal{T}^{sch}
\end{equation}

\begin{equation}
    -Inv_{r,t} + \sum_{p \in \mathcal{P}} P_{p,t} \times \eta(p,r) = 0 \hspace{1cm} \forall r \in \mathcal{R}^{stored}, t \in \mathcal{T}^{sch}
\end{equation}

\begin{equation}
    \sum_{p \in \mathcal{P}} P_{p,t} \times \eta(p,r) + C_{r,t} = 0 \hspace{1cm} \forall r \in \mathcal{R}^{cons}, t \in \mathcal{T}^{sch}
\end{equation}

\begin{equation}
    S_{r,t}, C_{r,t}, Inv_{r,t}, P_{p,t}, Cap^P_p, Cap^S_r \in R_{\geq 0}
\end{equation}




## mpLP reformulation

Reformulated as an mpLP


\begin{equation}
    min \hspace{1cm} \sum_{p \in \mathcal{P}} Capex_p \times \epsilon_p \times P_p + \sum_{r \in \mathcal{R}^{cons}} C_r \times \gamma_r 
\end{equation}


\begin{equation}
    Inv_r \leq Cap^{S-max}_r \hspace{1cm} \forall r \in \mathcal{R}^{stored}
\end{equation}

\begin{equation}
    - S_r \leq - D_r \times \beta_r \hspace{1cm} \forall r \in \mathcal{R}^{demand}
\end{equation}

\begin{equation}
    C_r \leq C^{max}_r \times \delta_r \hspace{1cm} \forall r \in \mathcal{R}^{cons} 
\end{equation}

\begin{equation}
    P_p \leq Cap^{P-max}_p \times \alpha_p \hspace{1cm} \forall p \in \mathcal{P}
\end{equation} 

\begin{equation}
    - S_{r} + \sum_{p \in \mathcal{P}} P_{p} \times \eta(p,r) = 0 \hspace{1cm} \forall r \in \mathcal{R}^{sell}
\end{equation}

\begin{equation}
    - Inv_{r} + \sum_{p \in \mathcal{P}} P_{p} \times \eta(p,r) = 0 \hspace{1cm} \forall r \in \mathcal{R}^{stored}
\end{equation}

\begin{equation}
    \sum_{p \in \mathcal{P}} P_{p} \times \eta(p,r) + C_{r} = 0 \hspace{1cm} \forall r \in \mathcal{R}^{cons}
\end{equation}

\begin{equation}
    \alpha_p \in A_p \hspace{1cm} \forall p \in \mathcal{P}
\end{equation}

\begin{equation}
    \beta_r \in B_r \hspace{1cm} \forall r \in \mathcal{R}^{demand}
\end{equation}

\begin{equation}
    \gamma_r \in \Gamma_r \hspace{1cm} \forall r \in \mathcal{R}^{cons}
\end{equation}

\begin{equation}
    \delta_r \in \Delta_r \hspace{1cm} \forall r \in \mathcal{R}^{cons}
\end{equation}

\begin{equation}
    \epsilon_p \in E_p \hspace{1cm} \forall p \in \mathcal{P}
\end{equation}


\begin{equation}
    S_r, C_r, Inv_r, P_p \in R_{\geq 0}
\end{equation}


## Example Problem


\begin{equation}
    p \in \{LI_c, LI_d, WF, PV\} 
\end{equation}


\begin{equation}
    r \in \{charge, power, wind, solar\} 
\end{equation}



\begin{equation}
    min \hspace{1cm} \left[\begin{matrix}1302\\0\\990\\567\end{matrix}\right]^T \left[\begin{matrix}P_{LI_c}\\P_{LI_d}\\P_{WF}\\P_{PV}\end{matrix}\right]
\end{equation}



\begin{equation}
    I_3\left[\begin{matrix}Inv_{charge}\\C_{wind}\\C_{solar}\\P_{LI_c}\\P_{LI_d}\end{matrix}\right] \leq \left[\begin{matrix} 100\\100\\100\\100\\100\end{matrix}\right]
\end{equation}



\begin{equation}
    I_3\left[\begin{matrix}-S_{power}\\P_{WF}\\P_{PV}\end{matrix}\right] \leq \left[\begin{matrix}-300 & 0 & 0\\0 & 100 & 0\\0 & 0 & 100\end{matrix}\right] \left[\begin{matrix}\beta_{power}\\ \alpha_{WF}\\\alpha_{PV}\end{matrix}\right]
\end{equation}



\begin{equation}
    I_4\left[\begin{matrix} - Inv_{charge} \\ -S_{power} \\ C_{wind} \\ C_{solar} \end{matrix}\right] + \left[\begin{matrix}0.89 & -1 & 0 & 0\\-1 & 1 & 0.85 & 0.75\\0 & 0 & -1 & 0\\0 & 0 & 0 & -1\end{matrix}\right] \left[\begin{matrix}P_{LI_c}\\P_{LI_d}\\P_{WF}\\P_{PV}\end{matrix}\right] = 0
\end{equation}



\begin{equation}
    \alpha_p \in \mathcal{A}_p \hspace{1cm} \forall p \in \{WF, PV\} 
\end{equation}

\begin{equation}
    \beta_r \in \mathcal{B}_r \hspace{1cm} \forall r \in \{Power\} 
\end{equation}

$\textbf{Import modules}$

In [1]:
from energia import *

m = Model(init=[si_units])

In [2]:
m.solar = Resource(basis=m.MW, label='Solar Power')
m.solar.consume <= 100
m.wind = Resource(basis=m.MW, label='Wind Power')
m.wind.consume <= 100
m.power = Resource(basis=m.MW, label='Power generated')
m.power.release == (120, 150)

--- General Resource Balance for solar in (l, t0): initializing constraint, adding consume(solar, l, t0)
    Completed in 0.0003628730773925781 seconds
--- Binding consume in domain (solar, l, t0)
    Completed in 0.00020933151245117188 seconds
--- General Resource Balance for wind in (l, t0): initializing constraint, adding consume(wind, l, t0)
    Completed in 0.00038814544677734375 seconds
--- Binding consume in domain (wind, l, t0)
    Completed in 0.00019311904907226562 seconds
--- General Resource Balance for power in (l, t0): initializing constraint, adding release(power, l, t0)
    Completed in 0.00025200843811035156 seconds
--- Binding release in domain (power, l, t0)
    Completed in 0.0002498626708984375 seconds


$\textbf{Declare processes}$

In [3]:
m.lii = Storage()

m.lii(m.power) == 0.9
m.power.lii.inventory == (10, 100)

# m.lii.capacity >= 10
# m.lii.capacity[m.money.spend] == 1302
m.power.lii.inventory[m.money.spend] == 2000
m.lii.charge.operate <= 25
m.lii.discharge.operate <= 25

--- General Resource Balance for power.lii in (l, t0): initializing constraint, adding inventory(power.lii, l, t0)
--- Binding inventory in domain (power.lii, l, t0)
    Completed in 0.0004189014434814453 seconds
--- Binding operate in domain (lii.charge, l, t0)
    Completed in 0.0002551078796386719 seconds
--- Binding operate in domain (lii.discharge, l, t0)
    Completed in 0.0001761913299560547 seconds


In [4]:
m.show()

# Mathematical Program for Program(m)

<br><br>

## Index Sets

<IPython.core.display.Math object>

<IPython.core.display.Math object>

<IPython.core.display.Math object>

<IPython.core.display.Math object>

<IPython.core.display.Math object>

<IPython.core.display.Math object>

<br><br>

## s.t.

### Bound Constraint Sets

<IPython.core.display.Math object>

<IPython.core.display.Math object>

<IPython.core.display.Math object>

<IPython.core.display.Math object>

<IPython.core.display.Math object>

<IPython.core.display.Math object>

### Calculation Constraint Sets

<IPython.core.display.Math object>

### General Resource Balance Constraint Sets

<IPython.core.display.Math object>

<IPython.core.display.Math object>

<IPython.core.display.Math object>

In [5]:
m.wf = Process()
m.wf(m.power) == -1 / 0.85 * m.wind
m.wf.operate == (0, 100)
m.wf.operate[m.money.spend] == 990

m.pv = Process()
m.pv(m.power) == -1 / 0.75 * m.solar
m.pv.operate == (0, 100)
m.pv.operate[m.money.spend] == 567

--- Binding operate in domain (wf, l, t0)
    Completed in 0.0003731250762939453 seconds
--- Binding operate in domain (pv, l, t0)
    Completed in 0.0001499652862548828 seconds


In [6]:
m.locate(m.pv, m.wf, m.lii)

--- Assuming  pv capacity is unbounded in (l, t0)
--- Assuming operation of pv is bound by capacity in (l, t0)
--- Binding operate in domain (pv, l, t0)
    Completed in 0.0002930164337158203 seconds
--- General Resource Balance for power in (l, t0): adding produce(power, l, t0, operate, pv)
    Completed in 0.00028204917907714844 seconds
--- General Resource Balance for solar in (l, t0): adding expend(solar, l, t0, operate, pv)
    Completed in 0.0003879070281982422 seconds
--- Assuming  wf capacity is unbounded in (l, t0)
--- Assuming operation of wf is bound by capacity in (l, t0)
--- Binding operate in domain (wf, l, t0)
    Completed in 0.0009367465972900391 seconds
--- General Resource Balance for power in (l, t0): adding produce(power, l, t0, operate, wf)
    Completed in 0.0002849102020263672 seconds
--- General Resource Balance for wind in (l, t0): adding expend(wind, l, t0, operate, wf)
    Completed in 0.00019598007202148438 seconds
--- Assuming  power.lii inventory capacity

In [9]:
m.money.spend.opt()

--- Mapping spend: (money, l, t0, inventory, power.lii) → (money, l, t0)
    Completed in 0.000s
--- Mapping spend: (money, l, t0, operate, wf) → (money, l, t0)
    Completed in 0.000s
--- Mapping spend: (money, l, t0, operate, pv) → (money, l, t0)
    Completed in 0.000s
--- Generating Program(m).mps
--- Creating gurobi model for Program(m)
Set parameter Username
Academic license - for non-commercial use only - expires 2025-12-16
Read MPS format model from file Program(m).mps
Reading time = 0.00 seconds
PROGRAM(M): 27 rows, 23 columns, 51 nonzeros
--- Optimizing Program(m) using gurobi
Gurobi Optimizer version 12.0.3 build v12.0.3rc0 (mac64[x86] - Darwin 21.6.0 21H1320)

CPU model: Intel(R) Core(TM) i7-6567U CPU @ 3.30GHz
Thread count: 2 physical cores, 4 logical processors, using up to 4 threads

Optimize a model with 27 rows, 23 columns and 51 nonzeros
Model fingerprint: 0xe6cdd64f
Coefficient statistics:
  Matrix range     [1e+00, 2e+03]
  Objective range  [1e+00, 1e+00]
  Bounds r

In [11]:
_m = m._.ppopt()

In [13]:
from ppopt.mp_solvers.solve_mpqp import solve_mpqp, mpqp_algorithm

sol = solve_mpqp(_m, mpqp_algorithm.geometric)

Using a found active set [0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 23, 24, 25, 28, 31]


In [14]:
sol

Solution(program=<ppopt.mplp_program.MPLP_Program object at 0x121974190>, critical_regions=[Critical region with active set [0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 23, 24, 25, 28, 31]
The Omega Constraint indices are [0, 1, 2, 3]
The Lagrange multipliers Constraint indices are []
The Regular Constraint indices are [[0, 1, 2, 3, 4, 5, 6, 7, 8], [20, 21, 22, 26, 27, 29, 30, 32, 33]]
  x(θ) = Aθ + b 
 λ(θ) = Cθ + d 
  Eθ <= f
 A = [[-5.21066366e-15 -1.77027258e-13 -3.04706857e-14  1.33333333e+00]
 [-2.70274117e-17  2.28000671e-13  1.17647059e+00  5.21660662e-14]
 [ 1.00000000e+00 -3.53581149e-13  1.02493741e-13  3.31012952e-14]
 [-1.55336877e-15  1.00000000e+00 -4.54477609e-14 -2.89050516e-14]
 [ 7.85781937e-13  2.00000000e+03 -2.85668781e-10 -4.79114558e-11]
 [-1.00000000e+01  9.61171444e-12  1.00000000e+01  1.00000000e+01]
 [-9.00000000e+00  8.72781866e-12  9.00000000e+00  9.00000000e+00]
 [ 3.51661027e-15  1.09242087e-13  1.00000000e+00  2.33320650e-14]
 

In [ ]:
solution = solve(matrix=matrix, interface='native', name='results_mplp', solver='ppopt')

In [ ]:
# solution

In [ ]:
len(solution.critical_regions)

In [ ]:
# solution.critical_regions[0]

In [ ]:
# from ppopt.plot import parametric_plot
# parametric_plot(solution)

In [ ]:
solution.evaluate_objective(numpy.array([[0.4], [0.6], [0.6]]))

In [ ]:
coordinates = []
from itertools import product

for i, j, k in product(
    numpy.linspace(0, 1, 50), numpy.linspace(0, 1, 50), numpy.linspace(0, 1, 50)
):
    l = solution.evaluate_objective(numpy.array([[i], [j], [k]]))
    if l is not None:
        coordinates.append((i, j, k, l[0][0]))

Unique solutions

In [ ]:
set([coordinates[i][3] for i in range(len(coordinates))])

In [ ]:
import matplotlib.pyplot as plt
from mpl_toolkits.mplot3d import Axes3D
from matplotlib import cm

# Sample data: (x, y, z, color_value)
data = coordinates
fig = plt.figure()
ax = fig.add_subplot(111, projection='3d')

x_vals, y_vals, z_vals, color_vals = zip(*data)

# Use color map to convert the color_value to a color
norm = plt.Normalize(min(color_vals), max(color_vals))
colors = cm.viridis(norm(color_vals))

scatter = ax.scatter(x_vals, y_vals, z_vals, c=colors, cmap='viridis', s=50)

# Add a color bar to show the mapping of color values
cbar = fig.colorbar(scatter, ax=ax, pad=0.1)
cbar.set_label('Fourth Dimension')

# ax.set_ylim(ax.get_xlim()[::-1])
# ax.set_ylim(ax.get_ylim()[::-1])
# ax.set_ylim(ax.get_zlim()[::-1])

ax.zorder = 0
ax.set_xlim(0, 1)
ax.set_ylim(0, 1)
ax.set_zlim(0, 1)

ax.set_xlabel('X Label')
ax.set_ylabel('Y Label')
ax.set_zlabel('Z Label')
plt.show()

In [ ]:
coordinates = [tuple(map(lambda x: 0 if x < 0.001 else x, i)) for i in coordinates]