In [17]:
from ppopt.mpmodel import MPModeler
from ppopt.mp_solvers.solve_mpqp import solve_mpqp, mpqp_algorithm
from ppopt.plot import parametric_plot_1D
from ppopt.plot import parametric_plot
from ppopt.mpqp_program import MPLP_Program
import numpy as np

In [2]:
# A = numpy.array([[1, 1, 0, 0], [0, 0, 1, 1], [-1, 0, -1, 0], [0, -1, 0, -1], [-1, 0, 0, 0], [0, -1, 0, 0], [0, 0, -1, 0], [0, 0, 0, -1]])
# b = numpy.array([350, 600, 0, 0, 0, 0, 0, 0]).reshape(8, 1)
# c = numpy.array([178, 187, 187, 151]).reshape(-1,1)
# F = numpy.array([[0, 0], [0, 0], [-1, 0], [0, -1], [0, 0], [0, 0], [0, 0], [0, 0]])
# CRa = numpy.vstack((numpy.eye(2), -numpy.eye(2)))
# CRb = numpy.array([1000, 1000, 0, 0]).reshape(4, 1)
# H = numpy.zeros((A.shape[1],F.shape[1]))
# 
# prog = MPLP_Program(A, b, c, H, CRa, CRb, F)

In [3]:
m = MPModeler()

x = m.add_var(name='x')
z = m.add_var(name='z')
u = m.add_var(name='u')

t1 = m.add_param(name='t1')
t2 = m.add_param(name='t2')
d1 = m.add_param(name='d1')
d2 = m.add_param(name='d2')

In [4]:
m.add_constr(-2*x +3*z == 50 +t1 - d2)
m.add_constr(x - z/2 -u <= -25 +t1/2 -t2/2 -d1 +7*d2/2)
m.add_constr(-2*x +2*z -u <= -151/3 +4*t1/3 +t2 -2*d2)
m.add_constr(-x + 5*z/2 -u <= 26 -t1/2 +t2 +d1 -d2/2)
m.add_constr(0 <= x)
m.add_constr(0 <= z)
m.add_constr(0 <= t1)
m.add_constr(0 <= t2)
m.add_constr(0 <= d1)
m.add_constr(0 <= d2)
m.add_constr(t1 <= 4)
m.add_constr(t2 <= 4)
m.add_constr(d1 <= 5)
m.add_constr(d2 <= 5)

In [5]:
m.set_objective(u-50)

In [6]:
prob = m.formulate_problem()
prob.process_constraints()

Set parameter Username
Academic license - for non-commercial use only - expires 2025-12-20


In [7]:
solution = solve_mpqp(prob, mpqp_algorithm.combinatorial)

In [13]:
solution

Solution(program=<ppopt.mplp_program.MPLP_Program object at 0x000002427813FEB0>, critical_regions=[Critical region with active set [0, 1, 2]
The Omega Constraint indices are [0, 1, 2, 3, 4, 5, 6, 7]
The Lagrange multipliers Constraint indices are []
The Regular Constraint indices are [[0], [3]]
  x(θ) = Aθ + b 
 λ(θ) = Cθ + d 
  Eθ <= f
 A = [[ 3.21472965e-16 -1.12500000e+00 -7.50000000e-01  3.50000000e+00]
 [ 3.33333333e-01 -7.50000000e-01 -5.00000000e-01  2.00000000e+00]
 [-6.66666667e-01 -2.50000000e-01  5.00000000e-01 -1.00000000e+00]] 
 b = [[50.25      ]
 [50.16666667]
 [50.16666667]] 
 C = [[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]] 
 d = [[-0.96824584]
 [ 2.        ]
 [ 1.98606255]] 
 E = [[ 0.45584231 -0.34188173 -0.45584231  0.68376346]
 [-1.          0.          0.          0.        ]
 [ 0.         -1.          0.          0.        ]
 [ 0.          0.         -1.          0.        ]
 [ 0.          0.          0.         -1.        ]
 [ 1.          0.          0.        

In [9]:
# # make a mpp modeler
# m = MPModeler()
# 
# # add variables and parameter
# u = m.add_var(name='u')
# z = m.add_var(name='z')
# t1 = m.add_param(name='t1')
# t3 = m.add_param(name='t3')
# t5 = m.add_param(name='t5')
# t8 = m.add_param(name='t8')
# 
# # add operability constraints
# m.add_constr(-z/1.5 - u <= 350 - t3)
# m.add_constr(-0.5*z - u <= -1388.5 + 0.75*t1 + t3 + t5)
# m.add_constr(z - u <= -2830 +1.5*t1 + 2*t3 + t5 + 2*t8)
# m.add_constr(z - u <= -2044 + 1.5*t1 + 2*t3 + t5)
# m.add_constr(-z - u <= 3153 - 1.5*t1 - 2*t3 - t5 - 3*t8)
# 
# # add constraints on the uncertainty
# m.add_constr(t1 <= 630)
# m.add_constr(t1 >= 610)
# m.add_constr(t3 <= 398)
# m.add_constr(t3 >= 378)
# m.add_constr(t5 <= 593)
# m.add_constr(t5 >= 573)
# m.add_constr(t8 <= 323)
# m.add_constr(t8 >= 303)
# 
# # set objective
# m.set_objective(u)
# 
# # formulate the model
# prob = m.formulate_problem()
# prob.process_constraints()

In [10]:
# solution = solve_mpqp(prog, mpqp_algorithm.combinatorial)

In [11]:
# solution

In [12]:
# parametric_plot(solution, save_path='transport', save_format='svg', show=True)

In [22]:
x = solution.evaluate_objective(np.array([0,0,0,0]))

In [23]:
x

0.1666666666666785