# mpLP reformulation of an energy systems MILP

__author__ = "Rahul Kakodkar"
__copyright__ = "Copyright 2023, Multi-parametric Optimization & Control Lab"
__credits__ = ["Rahul Kakodkar", "Dustin Kenefake", "Efstratios N. Pistikopoulos"]
__license__ = "Open"
__version__ = "1.0.0"
__maintainer__ = "Rahul Kakodkar"
__email__ = "cacodcar@tamu.edu"
__status__ = "Production"


## Problem Statement

In the following example a multi-scale energy systems mixed integer linear program (MILP) is reformulated as a mulitparametric linear program (mpLP)

## Nomenclature

*Sets*


$\mathcal{R}$ - set of all resources r

$\mathcal{P}$ - set of all processes p

$\mathcal{T}$ - set of temporal periods t


*Subsets*


$\mathcal{R}^{storage}$ - set of resources that can be stored

$\mathcal{R}^{sell}$ - set of resources that can be discharged

$\mathcal{R}^{demand}$ - set of resources that meet  demand

$\mathcal{R}^{cons}$ - set of resources that can be consumed

$\mathcal{P}^{uncertain-cap}$ - set of processes with uncertain capacity

$\mathcal{P}^{uncertain-capex}$ - set of processes with uncertain capital expenditure

$\mathcal{T}^{net}$ - set of temporal periods t for network level decision making

$\mathcal{T}^{sch}$ - set of temporal periods t for schedule level decision making


*Continuous Variables*


$P_{p,t}$ - production level of p $\in$  $\mathcal{P}$ in time period t $\in$ $\mathcal{T}^{sch}$  

$C_{r,t}$ - consumption of r $\in$ in $\mathcal{R}^{cons}$ time period t $\in$ $\mathcal{T}^{sch}$ 

$S_{r,t}$ - discharge of r $\in$ in $\mathcal{R}^{demand}$ time period t $\in$ $\mathcal{T}^{sch}$ 

$Inv_{r,t}$ - inventory level of r $\in$ $\mathcal{R}^{storage}$  in time period t $\in$ $\mathcal{T}^{sch}$

$Cap^S_{r,t}$ - installed inventory capacity for resource r $\in$  $\mathcal{R}^{storage}$ in time period t $\in$ $\mathcal{T}^{net}$

$Cap^P_{p,t}$ - installed production capacity for process p $\in$ $\mathcal{P}$ in time period t $\in$ $\mathcal{T}^{net}$




*Binary Variables*


$X^P_{p,t}$ - network binary for production process p $\in$ $\mathcal{P}$ in time period t $\in$ $\mathcal{T}^{net}$

$X^S_{r,t}$ - network binary for inventory of resource r  $\mathcal{R}^{storage}$ in time period t $\in$ $\mathcal{T}^{net}$



*Parametric Variables*


$\alpha_{p}$ - uncertainty in production capacity of process p $\in$ $\mathcal{P}^{uncertain-cap}$

$\beta_{r}$ - uncertainty in demand for resource r $\in$ $\mathcal{R}^{demand}$

$\gamma_{r}$ - uncertainty in purchase price for resource r $\in$ $\mathcal{R}^{cons}$

$\delta_{r}$ - uncertainty in consumption availability for resource r $\in$ $\mathcal{R}^{cons}$

$\epsilon_{p}$ - uncertainty in cost of technology for process p $\in$ $\mathcal{P}^{uncertain-capex}$



*Parameters*


$Cap^{P-max}_{p,t}$ - maximum production capacity of process p $\in$ $\mathcal{P}$ in time period t $\in$ $\mathcal{T}^{net}$

$Cap^{S-max}_{r,t}$ - maximum inventory capacity for process r $\in$ $\mathcal{R}^{storage}$ in time period t $\in$ $\mathcal{T}^{net}$

$Capex_{p,t}$ - capital expenditure for process p $\in$ $\mathcal{P}$ in time t $\in$ $\mathcal{T}^{net}$

$Vopex_{p,t}$ - variable operational expenditure for process p $\in$ $\mathcal{P}$ in time t $\in$ $\mathcal{T}^{sch}$

$Price_{r,t}$ - purchase price for resource r $\in$ $\mathcal{R}^{cons}$ in time t $\in$ $\mathcal{T}^{sch}$

$C^{max}_{r,t}$ - maximum consumption availability for resource r $\in$ $\mathcal{R}^{cons}$ in time t $\in$ $\mathcal{T}^{sch}$

$D_{r,t}$ - demand for resource r $in$ $\mathcal{R}^{sell}$ in time t $\in$ $\mathcal{T}^{sch}$




# MILP Formulation

Given is a general MILP modeling and optimization framework for simultaneous network design and scheduling.




\begin{equation}
    min \sum_{t \in \mathcal{T}^{net}} \sum_{p \in \mathcal{P}} Capex_{p,t} \times Cap^P_{p,t} + \sum_{t \in \mathcal{T}^{sch}} \sum_{r \in \mathcal{R}^{cons}}  Price_{r,t}  \times C_{r,t} + \sum_{t \in \mathcal{T}^{sch}} \sum_{p \in \mathcal{P}}  Vopex_{r,t} \times P_{r,t} 
\end{equation}


\begin{equation}
    Cap^S_{r,t} \leq Cap^{S-max}_{r,t} \times X^S_{r,t} \hspace{1cm} \forall r \in \mathcal{R}^{storage}, t \in \mathcal{T}^{net}
\end{equation}

\begin{equation}
    Cap^P_{p,t} \leq Cap^{P-max}_{p,t} \times X^P_p  \hspace{1cm} \forall p \in \mathcal{P}, t \in \mathcal{T}^{net}
\end{equation} 

\begin{equation}
    P_{p,t} \leq Cap^{P}_{p,t}  \hspace{1cm} \forall p \in \mathcal{P}, t \in \mathcal{T}^{sch}
\end{equation} 

\begin{equation}
    Inv_{r,t} \leq Cap^{S}_{r,t}  \hspace{1cm} \forall r \in \mathcal{R}^{storage}, t \in \mathcal{T}^{sch}
\end{equation} 


\begin{equation}
    - S_{r,t} \leq - D_{r,t}  \hspace{1cm} \forall r \in \mathcal{R}, t \in \mathcal{T}^{sch}
\end{equation}

\begin{equation}
    C_{r,t} \leq C^{max}_{r,t} \hspace{1cm} \forall r \in \mathcal{R}, t \in \mathcal{T}^{sch}
\end{equation}


\begin{equation}
    - S_{r,t} + \sum_{p \in \mathcal{P}} P_{p,t} \times \eta(p,r) = 0 \hspace{1cm} \forall r \in \mathcal{R}^{sell}, t \in \mathcal{T}^{sch}
\end{equation}

\begin{equation}
    -Inv_{r,t} + \sum_{p \in \mathcal{P}} P_{p,t} \times \eta(p,r) = 0 \hspace{1cm} \forall r \in \mathcal{R}^{stored}, t \in \mathcal{T}^{sch}
\end{equation}

\begin{equation}
    \sum_{p \in \mathcal{P}} P_{p,t} \times \eta(p,r) + C_{r,t} = 0 \hspace{1cm} \forall r \in \mathcal{R}^{cons}, t \in \mathcal{T}^{sch}
\end{equation}

\begin{equation}
    S_{r,t}, C_{r,t}, Inv_{r,t}, P_{p,t}, Cap^P_p, Cap^S_r \in R_{\geq 0}
\end{equation}




## mpLP reformulation

Reformulated as an mpLP


\begin{equation}
    min \hspace{1cm} \sum_{p \in \mathcal{P}} Capex_p \times \epsilon_p \times P_p + \sum_{r \in \mathcal{R}^{cons}} C_r \times \gamma_r 
\end{equation}


\begin{equation}
    Inv_r \leq Cap^{S-max}_r \hspace{1cm} \forall r \in \mathcal{R}^{stored}
\end{equation}

\begin{equation}
    - S_r \leq - D_r \times \beta_r \hspace{1cm} \forall r \in \mathcal{R}^{demand}
\end{equation}

\begin{equation}
    C_r \leq C^{max}_r \times \delta_r \hspace{1cm} \forall r \in \mathcal{R}^{cons} 
\end{equation}

\begin{equation}
    P_p \leq Cap^{P-max}_p \times \alpha_p \hspace{1cm} \forall p \in \mathcal{P}
\end{equation} 

\begin{equation}
    - S_{r} + \sum_{p \in \mathcal{P}} P_{p} \times \eta(p,r) = 0 \hspace{1cm} \forall r \in \mathcal{R}^{sell}
\end{equation}

\begin{equation}
    - Inv_{r} + \sum_{p \in \mathcal{P}} P_{p} \times \eta(p,r) = 0 \hspace{1cm} \forall r \in \mathcal{R}^{stored}
\end{equation}

\begin{equation}
    \sum_{p \in \mathcal{P}} P_{p} \times \eta(p,r) + C_{r} = 0 \hspace{1cm} \forall r \in \mathcal{R}^{cons}
\end{equation}

\begin{equation}
    \alpha_p \in A_p \hspace{1cm} \forall p \in \mathcal{P}
\end{equation}

\begin{equation}
    \beta_r \in B_r \hspace{1cm} \forall r \in \mathcal{R}^{demand}
\end{equation}

\begin{equation}
    \gamma_r \in \Gamma_r \hspace{1cm} \forall r \in \mathcal{R}^{cons}
\end{equation}

\begin{equation}
    \delta_r \in \Delta_r \hspace{1cm} \forall r \in \mathcal{R}^{cons}
\end{equation}

\begin{equation}
    \epsilon_p \in E_p \hspace{1cm} \forall p \in \mathcal{P}
\end{equation}


\begin{equation}
    S_r, C_r, Inv_r, P_p \in R_{\geq 0}
\end{equation}


## Example Problem


\begin{equation}
    p \in \{LI_c, LI_d, WF, PV\} 
\end{equation}


\begin{equation}
    r \in \{charge, power, wind, solar\} 
\end{equation}



\begin{equation}
    min \hspace{1cm} \left[\begin{matrix}1302\\0\\990\\567\end{matrix}\right]^T \left[\begin{matrix}P_{LI_c}\\P_{LI_d}\\P_{WF}\\P_{PV}\end{matrix}\right]
\end{equation}



\begin{equation}
    I_3\left[\begin{matrix}Inv_{charge}\\C_{wind}\\C_{solar}\\P_{LI_c}\\P_{LI_d}\end{matrix}\right] \leq \left[\begin{matrix} 100\\100\\100\\100\\100\end{matrix}\right]
\end{equation}



\begin{equation}
    I_3\left[\begin{matrix}-S_{power}\\P_{WF}\\P_{PV}\end{matrix}\right] \leq \left[\begin{matrix}-300 & 0 & 0\\0 & 100 & 0\\0 & 0 & 100\end{matrix}\right] \left[\begin{matrix}\beta_{power}\\ \alpha_{WF}\\\alpha_{PV}\end{matrix}\right]
\end{equation}



\begin{equation}
    I_4\left[\begin{matrix} - Inv_{charge} \\ -S_{power} \\ C_{wind} \\ C_{solar} \end{matrix}\right] + \left[\begin{matrix}0.89 & -1 & 0 & 0\\-1 & 1 & 0.85 & 0.75\\0 & 0 & -1 & 0\\0 & 0 & 0 & -1\end{matrix}\right] \left[\begin{matrix}P_{LI_c}\\P_{LI_d}\\P_{WF}\\P_{PV}\end{matrix}\right] = 0
\end{equation}



\begin{equation}
    \alpha_p \in \mathcal{A}_p \hspace{1cm} \forall p \in \{WF, PV\} 
\end{equation}

\begin{equation}
    \beta_r \in \mathcal{B}_r \hspace{1cm} \forall r \in \{Power\} 
\end{equation}

$\textbf{Import modules}$

In [1]:
import sys
sys.path.append('../../src')

In [2]:
from energiapy.components.result import Result
import polytope as pt
from ppopt.plot import parametric_plot
from ppopt.mp_solvers.solve_mpqp import solve_mpqp, mpqp_algorithm
from ppopt.mplp_program import MPLP_Program
from ppopt.mpqp_program import MPQP_Program
import numpy
import pandas
from energiapy.model.solve import solve
from energiapy.plot.plot_results import CostY, CostX
from energiapy.plot import plot_results, plot_scenario
from energiapy.model.formulate import formulate, Constraints, Objective, ModelClass
from energiapy.components.scenario import Scenario
from energiapy.components.location import Location
from energiapy.components.process import Process, VaryingProcess
from energiapy.components.resource import Resource, VaryingResource
from energiapy.components.material import Material
from energiapy.components.temporal_scale import TemporalScale


`polytope` failed to import `cvxopt.glpk`.
will use `scipy.optimize.linprog`


$\textbf{Define temporal scale}$


In [3]:
scales = TemporalScale(discretization_list=[1])


$\textbf{Declare resources}$

In [4]:
Solar = Resource(name='Solar', cons_max=100, basis='MW', label='Solar Power')

Wind = Resource(name='Wind', cons_max=100, basis='MW', label='Wind Power')

Power = Resource(name='Power', basis='MW', label='Power generated', varying = [VaryingResource.UNCERTAIN_DEMAND])


$\textbf{Declare processes}$

In [5]:
LiI = Process(name='LiI', storage=Power, capex=1302, fopex=0, vopex=0,  prod_max=50,
              storage_loss=0.11,  label='Lithium-ion battery', basis='MW', store_max=100)

WF = Process(name='WF', conversion={Wind: -1, Power: 0.85}, capex=990, fopex=0, vopex=0,
             prod_max=100, label='Wind mill array', basis='MW', varying=[VaryingProcess.UNCERTAIN_CAPACITY])

PV = Process(name='PV', conversion={Solar: -1, Power: 0.75}, capex=567, fopex=0, vopex=0,
             prod_max=100, label='Solar PV', basis='MW', varying=[VaryingProcess.UNCERTAIN_CAPACITY])



$\textbf{Declare location(s)}$


In [6]:
region = Location(name='region', processes={
                  LiI, PV, WF}, scales=scales, label='some region')


In [7]:
for i in region.resources_full:
    print(i, i.varying)

Power [<VaryingResource.UNCERTAIN_DEMAND: 5>]
LiI_Power_stored [<VaryingResource.STORED: 14>]
Wind [<VaryingResource.CERTAIN_AVAILABILITY: 11>, <VaryingResource.CERTAIN_PRICE: 10>]
Solar [<VaryingResource.CERTAIN_AVAILABILITY: 11>, <VaryingResource.CERTAIN_PRICE: 10>]


The combination of parameter data, locations, and transportation options generates a scenario. 

Scenarios are data sets that can be fed to models for analysis. 

In this case we are generating a scenario for the location houston. The scales need to be consistent.

In [8]:
example = Scenario(name='example', demand={region: {Power:150}}, network=region, scales=scales, label='example scenario')
# example = Scenario(name='example', demand={region: {Power: 50}}, network=region, scales=scales, label='example scenario')


In [9]:
lp = formulate(scenario=example, constraints={Constraints.COST, Constraints.INVENTORY,
                 Constraints.PRODUCTION, Constraints.RESOURCE_BALANCE}, objective=Objective.COST)

constraint process capex
constraint process fopex
constraint process vopex
constraint process incidental
constraint location capex
constraint location fopex
constraint location vopex
constraint location incidental
constraint network capex
constraint network fopex
constraint network vopex
constraint network incidental
constraint nameplate inventory
constraint storage max
constraint storage min
constraint production mode
constraint nameplate production
constraint production max
constraint production min
constraint inventory balance
constraint resource consumption
constraint resource purchase
constraint location production
constraint location discharge
constraint location consumption
constraint location purchase
constraint network production
constraint network discharge
constraint network consumption
constraint network purchase
constraint demand
objective cost


In [10]:
matrix = formulate(scenario=example, model_class=ModelClass.MPLP)


The problem has the following variables:
Resource inventory level (Inv) x 1
Exact resource discharge (Sf) x 0
Uncertain resource discharge (S) x 1
Exact resource availability (Af) x 2
Uncertain resource availability (A) x 0
Exact process production (Pf) x 2
Uncertain process production (P) x 2
 For a total of 8 (5 fixed, and 3 uncertain)


In [11]:
matrix['F'].shape

(20, 3)

In [12]:
matrix['b'].shape

(20, 1)

In [13]:
example.resource_set

{LiI_Power_stored, Power, Solar, Wind}

In [14]:
example.set_dict['resources_implicit']

[]

In [15]:
example.A_df

Inv_LiI_Power_stored  S_Power  Af_Solar  Af_Wind  Pf_LiI  \
0                   -1.0      0.0       0.0      0.0     1.0   
1                    0.0     -1.0       0.0      0.0    -1.0   
2                    0.0      0.0       1.0      0.0     0.0   
3                    0.0      0.0       0.0      1.0     0.0   
4                   -1.0      0.0       0.0      0.0     0.0   
5                    0.0     -1.0       0.0      0.0     0.0   
6                    0.0      0.0       1.0      0.0     0.0   
7                    0.0      0.0       0.0      1.0     0.0   
8                    0.0      0.0       0.0      0.0     1.0   
9                    0.0      0.0       0.0      0.0     0.0   
10                   0.0      0.0       0.0      0.0     0.0   
11                   0.0      0.0       0.0      0.0     0.0   
12                  -1.0     -0.0      -0.0     -0.0    -0.0   
13                  -0.0     -1.0      -0.0     -0.0    -0.0   
14                  -0.0     -0.0      -1.0     -0.0    -0.0   
15                  -0.0     -0.0      -0.0     -1.0    -0.0   
16                  -0.0     -0.0      -0.0     -0.0    -1.0   
17                  -0.0     -0.0      -0.0     -0.0    -0.0   
18                  -0.0     -0.0      -0.0     -0.0    -0.0   
19                  -0.0     -0.0      -0.0     -0.0    -0.0   

    Pf_LiI_discharge  P_PV  P_WF  
0              -1.00  0.00  0.00  
1               0.89  0.75  0.85  
2               0.00 -1.00  0.00  
3               0.00  0.00 -1.00  
4               0.00  0.00  0.00  
5               0.00  0.00  0.00  
6               0.00  0.00  0.00  
7               0.00  0.00  0.00  
8               0.00  0.00  0.00  
9               1.00  0.00  0.00  
10              0.00  1.00  0.00  
11              0.00  0.00  1.00  
12             -0.00 -0.00 -0.00  
13             -0.00 -0.00 -0.00  
14             -0.00 -0.00 -0.00  
15             -0.00 -0.00 -0.00  
16             -0.00 -0.00 -0.00  
17             -1.00 -0.00 -0.00  
18             -0.00 -1.00 -0.00  
19             -0.00 -0.00 -1.00

In [16]:
example.F_df

Th_Power  Th_PV  Th_WF
0        0.0    0.0    0.0
1        0.0    0.0    0.0
2        0.0    0.0    0.0
3        0.0    0.0    0.0
4        0.0    0.0    0.0
5      150.0    0.0    0.0
6        0.0    0.0    0.0
7        0.0    0.0    0.0
8        0.0    0.0    0.0
9        0.0    0.0    0.0
10       0.0  100.0    0.0
11       0.0    0.0  100.0
12       0.0    0.0    0.0
13       0.0    0.0    0.0
14       0.0    0.0    0.0
15       0.0    0.0    0.0
16       0.0    0.0    0.0
17       0.0    0.0    0.0
18       0.0    0.0    0.0
19       0.0    0.0    0.0

In [17]:

prog = MPLP_Program(matrix['A'], matrix['b'], matrix['c'], matrix['H'],
                    matrix['CRa'], matrix['CRb'], matrix['F'], equality_indices=[0, 1, 2, 3, 4, 5, 6])
prog.solver.solvers['lp'] = 'gurobi'
# prog.warnings()
# prog.display_warnings()
# prog.process_constraints()
solution1 = solve_mpqp(prog, mpqp_algorithm.combinatorial)


Set parameter Username
Academic license - for non-commercial use only - expires 2024-02-14


In [18]:
solution1.critical_regions

[]

In [19]:
prog = MPLP_Program(matrix['A'], matrix['b'], matrix['c'], matrix['H'],
                    matrix['CRa'], matrix['CRb'], matrix['F'], equality_indices=[0, 1, 2, 3])
prog.solver.solvers['lp'] = 'gurobi'
prog.warnings()
prog.display_warnings()
prog.process_constraints()
solution1 = solve_mpqp(prog, mpqp_algorithm.combinatorial)
# prog.solve_theta(numpy.array([[0.76816588], [0.6937343 ], [0.52326189]]))
print(solution1.critical_regions)


[]
[Critical region with active set [0, 1, 2, 3, 4, 5, 11, 15]
The Omega Constraint indices are [1, 2, 4, 5]
The Lagrange multipliers Constraint indices are []
The Regular Constraint indices are [[3, 7, 8, 10], [9, 14, 16, 18]]
  x(θ) = Aθ + b 
 λ(θ) = Cθ + d 
  Eθ <= f
 A = [[  -0.         0.         0.     ]
 [-150.         0.         0.     ]
 [   0.         0.         0.     ]
 [-176.47059    0.         0.     ]
 [   0.         0.         0.     ]
 [   0.         0.         0.     ]
 [   0.         0.         0.     ]
 [-176.47059    0.         0.     ]] 
 b = [[ -0.     ]
 [150.     ]
 [100.     ]
 [ 88.23529]
 [ -0.     ]
 [ -0.     ]
 [100.     ]
 [ 88.23529]] 
 C = [[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]] 
 d = [[ -1795.42349]
 [ -2351.75432]
 [  -433.49805]
 [    -0.     ]
 [174709.76466]
 [   306.52941]
 [  1036.58824]
 [  1430.11765]] 
 E = [[ 0. -1.  0.]
 [ 1.  0.  0.]
 [-1.  0.  0.]
 [ 1.  0.  0.]
 [ 0.  1.  0.]
 [ 0.

In [20]:
solution1.critical_regions[0].__dict__.keys()

dict_keys(['A', 'b', 'C', 'd', 'E', 'f', 'active_set', 'omega_set', 'lambda_set', 'regular_set', 'y_fixation', 'y_indices', 'x_indices'])

In [21]:
solution1.critical_regions[0]

Critical region with active set [0, 1, 2, 3, 4, 5, 11, 15]
The Omega Constraint indices are [1, 2, 4, 5]
The Lagrange multipliers Constraint indices are []
The Regular Constraint indices are [[3, 7, 8, 10], [9, 14, 16, 18]]
  x(θ) = Aθ + b 
 λ(θ) = Cθ + d 
  Eθ <= f
 A = [[  -0.         0.         0.     ]
 [-150.         0.         0.     ]
 [   0.         0.         0.     ]
 [-176.47059    0.         0.     ]
 [   0.         0.         0.     ]
 [   0.         0.         0.     ]
 [   0.         0.         0.     ]
 [-176.47059    0.         0.     ]] 
 b = [[ -0.     ]
 [150.     ]
 [100.     ]
 [ 88.23529]
 [ -0.     ]
 [ -0.     ]
 [100.     ]
 [ 88.23529]] 
 C = [[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]] 
 d = [[ -1795.42349]
 [ -2351.75432]
 [  -433.49805]
 [    -0.     ]
 [174709.76466]
 [   306.52941]
 [  1036.58824]
 [  1430.11765]] 
 E = [[ 0. -1.  0.]
 [ 1.  0.  0.]
 [-1.  0.  0.]
 [ 1.  0.  0.]
 [ 0.  1.  0.]
 [ 0.  0.

In [22]:
prog1 = MPLP_Program(matrix['A'], matrix['b'], matrix['c'], matrix['H'],
                     matrix['CRa'], matrix['CRb'], matrix['F'], equality_indices=[0, 1, 2, 3])
prog1.solver.solvers['lp'] = 'gurobi'
prog1.warnings()
prog1.display_warnings()
prog1.process_constraints()
solution2 = solve_mpqp(prog1, mpqp_algorithm.combinatorial)
print(solution2.critical_regions)


[]
[Critical region with active set [0, 1, 2, 3, 4, 5, 11, 15]
The Omega Constraint indices are [1, 2, 4, 5]
The Lagrange multipliers Constraint indices are []
The Regular Constraint indices are [[3, 7, 8, 10], [9, 14, 16, 18]]
  x(θ) = Aθ + b 
 λ(θ) = Cθ + d 
  Eθ <= f
 A = [[  -0.         0.         0.     ]
 [-150.         0.         0.     ]
 [   0.         0.         0.     ]
 [-176.47059    0.         0.     ]
 [   0.         0.         0.     ]
 [   0.         0.         0.     ]
 [   0.         0.         0.     ]
 [-176.47059    0.         0.     ]] 
 b = [[ -0.     ]
 [150.     ]
 [100.     ]
 [ 88.23529]
 [ -0.     ]
 [ -0.     ]
 [100.     ]
 [ 88.23529]] 
 C = [[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]] 
 d = [[ -1795.42349]
 [ -2351.75432]
 [  -433.49805]
 [    -0.     ]
 [174709.76466]
 [   306.52941]
 [  1036.58824]
 [  1430.11765]] 
 E = [[ 0. -1.  0.]
 [ 1.  0.  0.]
 [-1.  0.  0.]
 [ 1.  0.  0.]
 [ 0.  1.  0.]
 [ 0.

In [23]:
solution1


Solution(program=MPLP_Program(A=array([[-0.57735,  0.     ,  0.     ,  0.     ,  0.57735, -0.57735,
         0.     ,  0.     ],
       [ 0.     , -0.49525,  0.     ,  0.     , -0.49525,  0.44077,
         0.37144,  0.42096],
       [ 0.     ,  0.     ,  0.70711,  0.     ,  0.     ,  0.     ,
        -0.70711,  0.     ],
       [ 0.     ,  0.     ,  0.     ,  0.70711,  0.     ,  0.     ,
         0.     , -0.70711],
       [ 0.     , -0.00667,  0.     ,  0.     ,  0.     ,  0.     ,
         0.     ,  0.     ],
       [ 0.     ,  0.     ,  1.     ,  0.     ,  0.     ,  0.     ,
         0.     ,  0.     ],
       [ 0.     ,  0.     ,  0.     ,  1.     ,  0.     ,  0.     ,
         0.     ,  0.     ],
       [ 0.     ,  0.     ,  0.     ,  0.     ,  1.     ,  0.     ,
         0.     ,  0.     ],
       [ 0.     ,  0.     ,  0.     ,  0.     ,  0.     ,  1.     ,
         0.     ,  0.     ],
       [ 0.     ,  0.     ,  0.     ,  0.     ,  0.     ,  0.     ,
         0.01   ,  0.     ]

In [24]:
from ppopt.utils.constraint_utilities import find_redundant_constraints

pre_kept = find_redundant_constraints(numpy.block([[matrix['A'], -matrix['F']], [numpy.zeros(
    (matrix['CRa'].shape[0], 8)), matrix['CRa']]]), numpy.block([[matrix['b']], [matrix['CRb']]]), [0, 1, 2, 3])
pre_kept = list(filter(lambda x: x < 20, pre_kept))


In [25]:
prog2 = MPLP_Program(matrix['A'][pre_kept], matrix['b'][pre_kept], matrix['c'], matrix['H'],
                     matrix['CRa'], matrix['CRb'], matrix['F'][pre_kept], equality_indices=[0, 1, 2, 3])
prog2.solver.solvers['lp'] = 'gurobi'
prog2.warnings()
prog2.display_warnings()
# prog1.process_constraints()
solution3 = solve_mpqp(prog1, mpqp_algorithm.combinatorial)
print(len(solution3.critical_regions))


[]
2


In [26]:
len(solution1.critical_regions), len(
    solution2.critical_regions), len(solution3.critical_regions)


(2, 2, 2)

In [27]:
len(solution2.critical_regions)


2

In [28]:
# print(prog.A)
# prog.process_constraints()
# print(prog.num_constraints())

# print(prog.num_constraints())
# # print(prog.solve_theta(numpy.array([[0.76816588], [0.6937343 ], [0.52326189]])))
# print(prog.equality_indices)
# print(prog.A)
# print(prog.num_constraints())
# print([(A[i], prog.A[i]) for i in range(prog.num_constraints())])


In [29]:
# solution = solve_mpqp(prog, mpqp_algorithm.geometric)
# len(solution.critical_regions)
# A_prime = prog.A
# F_prime = prog.F
# A_tprime = prog.A_t


In [30]:
# solution1.critical_regions[0]


In [31]:
# solution.critical_regions[0].E@theta_point <= solution.critical_regions[0].f
# print(solution.critical_regions[0].E[3], solution.critical_regions[0].f[3])
cr = solution3.critical_regions[0]
new_theta = prog.solver.solve_lp(
    c=(prog.c.T@cr.A).reshape(-1, 1), A=cr.E, b=cr.f).sol
print(prog.solver.solve_lp(c=(prog.c.T@cr.A).reshape(-1, 1),
      A=cr.E, b=cr.f).obj + prog.c.T@cr.b)
cr.evaluate(new_theta.reshape(-1, 1))


[[56700.]]


array([[ -0.],
       [ 75.],
       [100.],
       [ -0.],
       [ -0.],
       [  0.],
       [100.],
       [ -0.]])

In [36]:
new_theta

array([0.5, 0. , 0. ])

In [32]:
cr = solution2.critical_regions[0]
new_theta = prog1.solver.solve_lp(
    c=(prog1.c.T@cr.A).reshape(-1, 1), A=cr.E, b=cr.f).sol
print(prog1.solver.solve_lp(c=(prog1.c.T@cr.A).reshape(-1, 1),
      A=cr.E, b=cr.f).obj + prog1.c.T@cr.b)
cr.evaluate(new_theta.reshape(-1, 1))


[[56700.]]


array([[ -0.],
       [ 75.],
       [100.],
       [ -0.],
       [ -0.],
       [  0.],
       [100.],
       [ -0.]])

In [37]:
cr.evaluate(new_theta.reshape(-1, 1))

array([[ -0.],
       [ 75.],
       [100.],
       [ -0.],
       [ -0.],
       [  0.],
       [100.],
       [ -0.]])

In [33]:
# [x.b for x in solution.critical_regions]
for i in range(1000):
    theta_samp = numpy.random.rand(3).reshape(-1, 1)

    prop = prog.solve_theta(theta_samp)

    if prop is not None:
        print(prop)
        print(theta_samp)
        break


SolverOutput(obj=array([[20765.3574]]), sol=array([ 0.     , 27.4674 , 36.62321,  0.     ,  0.     ,  0.     ,
       36.62321,  0.     ]), slack=array([  0.     ,   0.     ,   0.     ,   0.     ,   0.     ,  63.37679,
       100.     ,  50.     ,  50.     ,   1.22159,   1.44627,   0.     ,
        27.4674 ,  36.62321,   0.     ,   0.     ,   0.     ,  36.62321,
         0.     ]), active_set=array([ 0,  1,  2,  3,  4, 11, 14, 15, 16, 18], dtype=int64), dual=array([   3564.56056,    1526.50235,       0.     ,       0.     ,
       -113402.51997,       0.     ,       0.     ,       0.     ,
             0.     ,       0.     ,       0.     ,   -2058.     ,
             0.     ,       0.     ,       0.     ,       0.     ,
         -1385.16   ,       0.     ,    -347.4    ]))
[[0.81688]
 [0.58789]
 [0.44635]]


In [34]:
# [x.b for x in solution.critical_regions]
for i in range(1000):
    theta_samp = numpy.random.rand(3).reshape(-1, 1)

    prop = prog2.solve_theta(theta_samp)

    if prop is not None:
        print(prop)
        print(theta_samp)
        break


SolverOutput(obj=array([[67962.87115]]), sol=array([  0.     ,  84.67014, 100.     ,  11.37664,   0.     ,   0.     ,
       100.     ,  11.37664]), slack=array([  0.     ,   0.     ,   0.     ,   0.     ,   0.     ,   0.     ,
        88.62336,  50.     ,  50.     ,  19.96087, 156.33325,   0.     ,
        84.67014, 100.     ,  11.37664,   0.     ,   0.     , 100.     ,
        11.37664]), active_set=array([ 0,  1,  2,  3,  4,  5, 11, 15, 16], dtype=int64), dual=array([ 2466.70588,  1164.70588,   306.52941,     0.     , -1164.70588,
        -306.52941,     0.     ,     0.     ,     0.     ,     0.     ,
           0.     , -2466.70588,     0.     ,     0.     ,     0.     ,
           0.     , -1430.11765,     0.     ,     0.     ]))
[[0.43553]
 [0.19961]
 [0.6771 ]]


In [35]:

A_poly = numpy.block([[A, -F], [numpy.zeros((6, 16)), CRa]])
b_poly = numpy.block([[b], [CRb]])


NameError: name 'A' is not defined

In [ ]:
from itertools import product
from pyomo.environ import Set, Constraint, NonNegativeReals, ConcreteModel, Var
from energiapy.utils.latex_utils import constraint_latex_render
import sys
sys.path.append('../src')
instance = ConcreteModel()
instance.transport = Set(initialize=list(range(4)))
instance.location = Set(initialize=list(range(4)))
instance.network = Set(initialize=list(range(4)))
instance.price = Var(instance.transport, within=NonNegativeReals)
instance.cons_max = Var(instance.transport, instance.location,
                        instance.network, within=NonNegativeReals)


def rule(instance, transport):
    return instance.price[transport] == sum(instance.cons_max[transport, location, network] for location, network in product(instance.location, instance.network))


instance.networkons = Constraint(instance.transport, rule=rule)


In [ ]:
constraint_latex_render(rule)


In [ ]:
def rule()
